global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692'] # RabbitMQ Prometheus plugin port

  - job_name: 'orion-ld'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['orion-ld:1026']

  # - job_name: 'coreapi'
  #   metrics_path: '/metrics'
  #   static_configs:
  #     - targets: ['coreapi:80']
